# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: HoopTrack
site_description: Simply take your basketball stats over a video automatically
site_url: https://todo.com

repo_name: MathisNcl/HoopTrack
repo_url: https://github.com/MathisNcl/HoopTrack

theme:
  name: 'material'
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - announce.dismiss
    - navigation.tabs

nav:
  - Intro:
    - index.md
  - Tutorials:
    - tutorials/00_GettingStarted.md
  - Methodology:
    - methodology/methodology_yolo.md
  - Contributions:
    - contribute/thanks.md

markdown_extensions:
  mdx_include:
    base_path: docs
  tables:
  admonition:
  pymdownx.details:
  pymdownx.arithmatex:
    generic: true
#  pymdownx.extra:
  pymdownx.tabbed:
    alternate_style: true
  pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
  pymdownx.inlinehilite:
  pymdownx.snippets:
    dedent_subsections: true
  pymdownx.superfences:
  attr_list:
  md_in_html:

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
